version: '3.8'
services:
  garagedb:
    image: mongo
    container_name: garagedb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./database/docker:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped